### ISSUE TITLE
Want a complete project, research reproduction

### ISSUE THREAD

**Issue by the-king-of-yhq** [Cihsaing/rvsl-robust-vehicle-similarity-learning--ECCV22#1]
I used the link you attached to the paper, I didn't find the complete project on github, I hope to reproduce it, can you give you the complete project? thanks

**Comment by AaronCIH** [comment]
Hi, I update the complete code. Please try that again.
If you have any question, please let me know. 

Thanks.

**Comment by frensher** [comment]
> Hi, I update the complete code. Please try that again. If you have any question, please let me know.
> 
> Thanks.

where is the paper? please

**Comment by AaronCIH** [comment]
@frensher  
Hi, the ECCV paper will be published in main conference on Oct.23~27.
In advance, we also provide the arXiv version. 
https://arxiv.org/abs/2209.08630

Thank you!

**Comment by the-king-of-yhq** [comment]
I want the Vehicle 1M datasets,I contact the [haiyun.gao@nplr.ia.ac.cn](mailto:haiyun.gao@nplr.ia.ac.cn),but he doesn't reply me.Can you provide it with me?
