### ISSUE TITLE
about  results

### ISSUE THREAD

**Issue by frensher** [Cihsaing/rvsl-robust-vehicle-similarity-learning--ECCV22#2]
![图片](https://user-images.githubusercontent.com/42425485/195606512-b8901fe4-c457-49d8-b912-d661f0a428fc.png)
hi
i want to ask that where is the result in sys_test?
![图片](https://user-images.githubusercontent.com/42425485/195606803-f92b1088-f51c-41fc-a7a7-2bfb3222d381.png)
i just find test in real.  do not train -all.

**Comment by the-king-of-yhq** [comment]
I want the Vehicle 1M datasets,I contact the haiyun.gao@nplr.ia.ac.cn,but he doesn't reply me.Can you provide it with me?
